name: Doug Land. Art
favicon: null
layout_spectrum: 0.75582
typography_spectrum: 0.88166
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbf9fe'
    - '#bfaadf'
    - '#2b0a4f'
    - '#a15ec9'
    - '#6b429b'
  brandStrength: 0.6875
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
