name: Doug Land. Art
favicon: null
layout_spectrum: 0.24955
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0b0b'
    - '#00434c'
    - '#00666b'
    - '#1ca1aa'
    - '#aabc94'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
